% ------------------------------------------------------------------------------
% Create configuration parameter lists of decoder names and NetCDF names.
%
% SYNTAX :
%  [o_decArgoConfParamNames, o_ncConfParamNames] = ...
%    create_config_param_names_apx_ir_rudics(a_decoderId)
%
% INPUT PARAMETERS :
%    a_decoderId : decoder Id
%
% OUTPUT PARAMETERS :.
%    o_decArgoConfParamNames : internal configuration parameter names
%    o_ncConfParamNames      : NetCDF configuration parameter names
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   07/10/2017 - RNU - creation
% ------------------------------------------------------------------------------
function [o_decArgoConfParamNames, o_ncConfParamNames] = ...
   create_config_param_names_apx_ir_rudics(a_decoderId)

% output parameters initialization
o_decArgoConfParamNames = [];
o_ncConfParamNames = [];

% current float WMO number
global g_decArgo_floatNum;

% output NetCDF configuration parameter Ids
global g_decArgo_outputNcConfParamId;

% output NetCDF configuration parameter labels
global g_decArgo_outputNcConfParamLabel;


% create configuration names for decoder and associated one for NetCDF
decConfNames = [];
ncConfNames = [];
switch (a_decoderId)
   
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   
   case {1101, 1110, 1112}
      % 030410, 092813, 102815
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CHR'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FLBB'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   case {1102}
      % 120210
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_IMLT'} ...
         {'CONFIG_ICEM'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_RAFOS'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   case {1103, 1104, 1106, 1107}
      % 012811, 020212, 060612, 062813_1
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CHR'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   case {1105}
      % 030512
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FLBB'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_IDP'} ...
         {'CONFIG_IEP'} ...
         {'CONFIG_IMLT'} ...
         {'CONFIG_ICEM'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_RAFOS'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   case {1108, 1109, 1113}
      % 062813_2, 062813_3, 110216
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_IDP'} ...
         {'CONFIG_IEP'} ...
         {'CONFIG_IMLT'} ...
         {'CONFIG_ICEM'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_RAFOS'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   case {1111}
      % 073014
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CHR'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FLBB'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_IDP'} ...
         {'CONFIG_IEP'} ...
         {'CONFIG_IMLT'} ...
         {'CONFIG_ICEM'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   case {1201}
      % 061113
      
      configIds = [ ...
         {'CONFIG_ASCEND'} ...
         {'CONFIG_NUDGE'} ...
         {'CONFIG_IBN'} ...
         {'CONFIG_CTO'} ...
         {'CONFIG_CPAP'} ...
         {'CONFIG_CT'} ...
         {'CONFIG_DB'} ...
         {'CONFIG_TPP'} ...
         {'CONFIG_DPDP'} ...
         {'CONFIG_DPF'} ...
         {'CONFIG_TP'} ...
         {'CONFIG_DOWN'} ...
         {'CONFIG_FEXT'} ...
         {'CONFIG_FRET'} ...
         {'CONFIG_HPVE'} ...
         {'CONFIG_HPVR'} ...
         {'CONFIG_TBP'} ...
         {'CONFIG_MLS'} ...
         {'CONFIG_PRE'} ...
         {'CONFIG_OIAM'} ...
         {'CONFIG_OTPO'} ...
         {'CONFIG_OVO'} ...
         {'CONFIG_OK'} ...
         {'CONFIG_PACT'} ...
         {'CONFIG_PPP'} ...
         {'CONFIG_PDP'} ...
         {'CONFIG_PRKP'} ...
         {'CONFIG_N'} ...
         {'CONFIG_DIR'} ...
         {'CONFIG_TRI'} ...
         {'CONFIG_TOD'} ...
         {'CONFIG_UP'} ...
         {'CONFIG_DEBUG'} ...
         ];
      
      for idC = 1:length(configIds)
         decConfNames{end+1} = configIds{idC};
         idParamName = find(strcmp(g_decArgo_outputNcConfParamId, decConfNames{end}) == 1);
         ncConfNames{end+1} = g_decArgo_outputNcConfParamLabel{idParamName};
      end
      
   otherwise
      fprintf('WARNING: Float #%d: Nothing implemented yet for decoderId #%d\n', ...
         g_decArgo_floatNum, ...
         a_decoderId);
end

% output for check
% for id = 1:length(decConfNames)
%    fprintf('%s;%s\n', decConfNames{id}, ncConfNames{id});
% end

% update output parameters
o_decArgoConfParamNames = decConfNames;
o_ncConfParamNames = ncConfNames;

return;
