% ------------------------------------------------------------------------------
% Get the basic structure to store Apex Iridium Rudics cycle timming information.
%
% SYNTAX :
%  [o_timeStruct] = get_apx_ir_rudics_float_time_init_struct
%
% INPUT PARAMETERS :
%
% OUTPUT PARAMETERS :
%   o_timeStruct : cycle timing structure
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   07/10/2017 - RNU - creation
% ------------------------------------------------------------------------------
function [o_timeStruct] = get_apx_ir_rudics_float_time_init_struct

% FOR APEX IRIDIUM RUDICS
% parkEndDateBis is finally NOT USED (not reliable when compared with
% parkEndDate)
% see: 6900796 for cycles >= 36 (once DOWN_TIME has been reduced)
% see: 6902549 for cycles >= 22 (once DOWN_TIME has been reduced)

% FOR NAVIS
% no example of such inconsistencies => parkEndDateBis is used (as a second
% choice)

o_timeStruct = struct( ...
   'cycleNum', [], ...
   'cycleStartDate', [], ...
   'cycleStartAdjDate', [], ...
   'descentStartDate', [], ...
   'descentStartAdjDate', [], ...
   'descentStartSurfPres', [], ...
   'descentStartDateBis', [], ... % computed as PST - ParkDescentTime (PST = time of the first drift meas)
   'descentStartAdjDateBis', [], ...
   'descentEndDate', [], ... % computed as time of first drift sample within 3% of aimed drift pressure
   'descentEndAdjDate', [], ...
   'parkStartDate', [], ...
   'parkStartAdjDate', [], ...
   'parkEndDate', [], ...
   'parkEndAdjDate', [], ...
   'parkEndMeas', [], ...
   'parkEndDateBis', [], ... % computed as descentStartDateBis + DOWN_TIME - DeepProfileDescentTime (if PARK_PRES ~= PROF_PRES) and descentStartDateBis + DOWN_TIME otherwise
   'parkEndAdjDateBis', [], ...
   'ascentStartDate', [], ...
   'ascentStartAdjDate', [], ...
   'ascentStartPres', [], ...
   'ascentStartAdjPres', [], ...
   'ascentEndDate', [], ...
   'ascentEndAdjDate', [], ...
   'ascentEndSurfPres', [], ...
   'ascentEndPres', [], ...
   'ascentEndAdjPres', [], ...
   'transStartDate', [], ... % of the previous cycle !
   'transStartDateMTime', [], ... % of the previous cycle !
   'transStartAdjDate', [], ... % of the previous cycle !
   'transEndDate', [], ... % of the previous cycle !
   'transEndDateMTime', [], ... % of the previous cycle !
   'transEndAdjDate', [] ... % of the previous cycle !
   );

return;
