% ------------------------------------------------------------------------------
% Get the list of primary parameters.
%
% SYNTAX :
%  [o_paramList] = get_primary_parameter_list(a_decoderId)
%
% INPUT PARAMETERS :
%   a_decoderId : float decoder Id
%
% OUTPUT PARAMETERS :
%   o_paramList : primary parameter list
%
% EXAMPLES :
%
% SEE ALSO : 
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   03/24/2015 - RNU - creation
% ------------------------------------------------------------------------------
function [o_paramList] = get_primary_parameter_list(a_decoderId)

% output parameters initialization
o_paramList = [];

% current float WMO number
global g_decArgo_floatNum;


switch (a_decoderId)
   case {1, 3, 11, 12, 17, 24, 30}
      
      % core Argos floats
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         ];
      
   case {4, 19, 25}
      
      % DO Argos floats
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         {'MOLAR_DOXY'} ...
         {'DOXY'} ...
         ];
      
   case {27, 28, 29}
      
      % DO Argos floats
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         {'TPHASE_DOXY'} ...
         {'DOXY'} ...
         ];

   case {105, 106, 107, 109}

      % remocean floats
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         {'TEMP_STD'} ...
         {'PSAL_STD'} ...
         {'PRES_MED'} ...
         {'TEMP_MED'} ...
         {'PSAL_MED'} ...
         ];
      
   case {201, 202, 203, 206, 207, 208}
      
      % Arvor Deep
      % Provor-DO Iridium
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         {'C1PHASE_DOXY'} ...
         {'C2PHASE_DOXY'} ...
         {'TEMP_DOXY'} ...
         {'DOXY'} ...
         ];
      
   case {209}
      
      % Arvor-2DO Iridium
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         {'C1PHASE_DOXY'} ...
         {'C2PHASE_DOXY'} ...
         {'TEMP_DOXY'} ...
         {'DOXY'} ...
         {'PHASE_DELAY_DOXY'} ...
         {'TEMP_DOXY2'} ...
         {'DOXY2'} ...
         ];
      
   case {204, 205}

      % Arvor Iridium
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         ];
      
   otherwise
      fprintf('WARNING: Float #%d: No default primary parameters defined yet for decoderId #%d => using PRES, TEMP, PSAL\n', ...
         g_decArgo_floatNum, ...
         a_decoderId);
      
      o_paramList = [ ...
         {'PRES'} ...
         {'TEMP'} ...
         {'PSAL'} ...
         ];
end

return;
