% ------------------------------------------------------------------------------
% Print one packet of float programmed technical data in output CSV file.
%
% SYNTAX :
%  print_float_prog_tech_data_in_csv_file_111_113_to_116_one( ...
%    a_cycleNum, a_profNum, a_dataIndex, ...
%    a_floatProgTech)
%
% INPUT PARAMETERS :
%   a_cycleNum       : cycle number of the packet
%   a_profNum        : profile number of the packet
%   a_dataIndex      : index of the packet
%   a_floatProgTech  : float programmed technical data
%
% OUTPUT PARAMETERS :
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   03/19/2018 - RNU - creation
% ------------------------------------------------------------------------------
function print_float_prog_tech_data_in_csv_file_111_113_to_116_one( ...
   a_cycleNum, a_profNum, a_dataIndex, ...
   a_floatProgTech)

% current float WMO number
global g_decArgo_floatNum;

% output CSV file Id
global g_decArgo_outputCsvFileId;

fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; Packet time; %s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   julian_2_gregorian_dec_argo(a_floatProgTech(a_dataIndex, 1)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; Cycle #; %d\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 2));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; Profile #; %d\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 3));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% TECHNICAL PARAMETERS

fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT0 - Max eV activation at the surface (csec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 4), sprintf('<PT 0 %d>', a_floatProgTech(a_dataIndex, 4)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT1 - Number of valve activations target; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 5), sprintf('<PT 1 %d>', a_floatProgTech(a_dataIndex, 5)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT2 - Pressure timing period during buoyancy reduction; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 6), sprintf('<PT 2 %d>', a_floatProgTech(a_dataIndex, 6)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT3 - Pressure timing period during ascent (min); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 7), sprintf('<PT 3 %d>', a_floatProgTech(a_dataIndex, 7)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT4 - Max volume eV during descent and repositioning; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 8), sprintf('<PT 4 %d>', a_floatProgTech(a_dataIndex, 8)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT5 - Max pump duration during repositioning (csec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 9), sprintf('<PT 5 %d>', a_floatProgTech(a_dataIndex, 9)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT6 - Pump duration during ascent (csec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 10), sprintf('<PT 6 %d>', a_floatProgTech(a_dataIndex, 10)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT7 - Pump duration for surfacing (csec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 11), sprintf('<PT 7 %d>', a_floatProgTech(a_dataIndex, 11)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT8 - Pressure delta for repositioning (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 12), sprintf('<PT 8 %d>', a_floatProgTech(a_dataIndex, 12)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT9 - Max pressure before emergency ascent (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 13), sprintf('<PT 9 %d>', a_floatProgTech(a_dataIndex, 13)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT10 - First threshold for buoyancy reduction (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 14), sprintf('<PT 10 %d>', a_floatProgTech(a_dataIndex, 14)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT11 - Second threshold for buoyancy reduction (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 15), sprintf('<PT 11 %d>', a_floatProgTech(a_dataIndex, 15)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT12 - Repositioning threshold (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 16), sprintf('<PT 12 %d>', a_floatProgTech(a_dataIndex, 16)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT13 - Grounding mode (0 = pressure switch, 1 = stay grounded); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 17), sprintf('<PT 13 %d>', a_floatProgTech(a_dataIndex, 17)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT14 - Max volume before detecting grounding (cm3); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 18), sprintf('<PT 14 %d>', a_floatProgTech(a_dataIndex, 18)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT15 - Grounding pressure (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 19), sprintf('<PT 15 %d>', a_floatProgTech(a_dataIndex, 19)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT16 - Grounding switch pressure (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 20), sprintf('<PT 16 %d>', a_floatProgTech(a_dataIndex, 20)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT17 - Pressure delta during drift (dbar); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 21), sprintf('<PT 17 %d>', a_floatProgTech(a_dataIndex, 21)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT18 - Average descent speed (mm/sec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 22), sprintf('<PT 18 %d>', a_floatProgTech(a_dataIndex, 22)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT19 - Min ascent speed (mm/sec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 23), sprintf('<PT 19 %d>', a_floatProgTech(a_dataIndex, 23)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT20 - Average ascent speed (mm/sec); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 24), sprintf('<PT 20 %d>', a_floatProgTech(a_dataIndex, 24)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT21 - Waiting period on surface after emergency ascent (min); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 25), sprintf('<PT 21 %d>', a_floatProgTech(a_dataIndex, 25)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT22 - Volume to transfer after buoyancy reduction phase (cm3); %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 26), sprintf('<PT 22 %d>', a_floatProgTech(a_dataIndex, 26)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT 23 - Number of retries per SBD commands on error; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 27), sprintf('<PT 23 %d>', a_floatProgTech(a_dataIndex, 27)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT 24 - Buoyancy inversion : Offset pressure; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 28), sprintf('<PT 24 %d>', a_floatProgTech(a_dataIndex, 28)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT 25 - Buoyancy inversion : Volume of first EV activation; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 29), sprintf('<PT 25 %d>', a_floatProgTech(a_dataIndex, 29)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT 26 - Buoyancy inversion : Volume of next EV activation; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 30), sprintf('<PT 26 %d>', a_floatProgTech(a_dataIndex, 30)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT 27 - Buoyancy inversion : Maximum volume of EV activation; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 31), sprintf('<PT 27 %d>', a_floatProgTech(a_dataIndex, 31)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT28 - Coef 1; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 32), sprintf('<PT 28 %d>', a_floatProgTech(a_dataIndex, 32)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog tech; PT29 - Coef 2; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 33), sprintf('<PT 29 %d>', a_floatProgTech(a_dataIndex, 33)));

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ICE PARAMETERS

fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 0 - Ice detection : Nb day without emergence; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 34), sprintf('<PG 0 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 1 - Ice detection : Nb day before forcing an emergence; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 35), sprintf('<PG 1 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 2 - Algo ISA : Nb of ISA detections before ice confirmation; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 36), sprintf('<PG 2 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 3 - Algo ISA : Threshold pressure of deceleration; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 37), sprintf('<PG 3 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 4 - Algo ISA : Scrutation delay of speed; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 38), sprintf('<PG 4 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 5 - Algo ISA : Minimum speed; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 39), sprintf('<PG 5 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 6 - Algo ISA : Pump activation delay; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 40), sprintf('<PG 6 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 7 - Satellite mask : GPS session timeout to consider a masking; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 41), sprintf('<PG 7 %d>', a_floatProgTech(a_dataIndex, 34)));
fprintf(g_decArgo_outputCsvFileId, '%d; %d; %d; %s; float prog ice; PG 8 - Ascent hanging : Pump volume to consider an hanging on ascent; %d;;%s\n', ...
   g_decArgo_floatNum, a_cycleNum, a_profNum, get_phase_name(-1), ...
   a_floatProgTech(a_dataIndex, 42), sprintf('<PG 8 %d>', a_floatProgTech(a_dataIndex, 34)));

return
